import 'dart:async';
import 'dart:convert';
import 'dart:developer' as developer;
import 'dart:math';

import 'package:http/http.dart' as http;

import 'anime_model.dart';
import 'episode_model.dart';
import 'voice_actor_model.dart';

// ---------------------------------------------------------------------------
// Models — nama & shape dipertahankan sama seperti sebelumnya supaya
// anime_detail_screen.dart dan pemanggil lain tidak perlu berubah.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Custom-catalog guard — IDs generated by CatalogManagerScreen look like
// "custom-<timestamp>" and are 100% local (CatalogStore), never present on
// Jikan/AniList. Hitting either API for these just burns 16-45s to fail.
// ---------------------------------------------------------------------------
bool _isCustomCatalogId(String id) => id.startsWith('custom-');

class JikanAnimeDetail {
  final String title;
  final String synopsis;
  final double score;
  final int? rank;
  final int? episodes;
  final String status;
  final List<String> genres;
  final List<String> studios;
  final String largeImageUrl;
  final String? trailerYoutubeId;
  final List<RelatedAnimeModel> relations;

  const JikanAnimeDetail({
    required this.title,
    required this.synopsis,
    required this.score,
    required this.rank,
    required this.episodes,
    required this.status,
    required this.genres,
    required this.studios,
    required this.largeImageUrl,
    this.trailerYoutubeId,
    this.relations = const [],
  });
}

class CharacterVoiceActor {
  final String name;
  final String language;
  final String imageUrl;
  const CharacterVoiceActor({
    required this.name,
    required this.language,
    required this.imageUrl,
  });
}

class CharacterModel {
  final String malId;
  final String name;
  final String imageUrl;
  final String role;
  final List<CharacterVoiceActor> voiceActors;
  const CharacterModel({
    required this.malId,
    required this.name,
    required this.imageUrl,
    required this.role,
    required this.voiceActors,
  });
}

class ReviewModel {
  final String username;
  final String userImageUrl;
  final int score;
  final String review;
  final String date;
  const ReviewModel({
    required this.username,
    required this.userImageUrl,
    required this.score,
    required this.review,
    required this.date,
  });
}

class RelatedAnimeModel {
  final String malId;
  final String title;
  final String imageUrl;
  final String relationType;
  const RelatedAnimeModel({
    required this.malId,
    required this.title,
    required this.imageUrl,
    required this.relationType,
  });
}

// ---------------------------------------------------------------------------
// AnimeApiService — Jikan (MyAnimeList) only.
//
// Sebelumnya app ini pakai AniList GraphQL (lewat proxy Cloudflare Worker
// pihak ketiga) untuk detail/recommendations/characters, dan Jikan hanya
// untuk episodes. Proxy itu menolak request dari Flutter Web (403), dan
// AniList langsung tanpa proxy juga rawan CORS di browser.
//
// Jikan sudah terbukti CORS-friendly untuk browser (episodes selalu
// berhasil load) dan menyediakan semua data yang dibutuhkan (detail,
// recommendations, characters + voice actors, reviews) dalam satu API —
// jadi seluruh service sekarang Jikan-only. Tidak ada lagi MAL↔AniList ID
// mapping, tidak ada lagi proxy pihak ketiga.
// ---------------------------------------------------------------------------

class AnimeApiService {
  static bool get isTestMode => false;

  static const _jikanBase = 'https://api.jikan.moe/v4';

  // ── Memory cache ─────────────────────────────────────────────────────────
  static final Map<String, List<AnimeModel>>      _listCache    = {};
  static final Map<String, JikanAnimeDetail>       _detailCache  = {};
  static final Map<String, List<CharacterModel>>   _charCache    = {};
  static final Map<String, List<VoiceActorModel>>  _vaCache      = {};
  static final Map<String, List<AnimeModel>>       _recoCache    = {};
  static final Map<String, List<EpisodeModel>>     _episodeCache = {};
  static final Map<String, String?>                _coverCache   = {};

  // ── Jikan rate-limit guard ────────────────────────────────────────────
  // Jikan's own docs require a minimum 4-second gap between requests for
  // normal (non-bulk) usage. The previous 420ms gap was far below that,
  // which very likely contributed to the 429/504 responses seen under any
  // concurrent load (detail + episodes + characters + recommendations all
  // firing together from one screen).
  static DateTime _lastJikanRequest = DateTime.fromMillisecondsSinceEpoch(0);
  // Jikan's documented limit is roughly 3 req/s with a small burst
  // allowance — 1500ms was already conservative on paper, but with a whole
  // grid of posters (20-30+) queued behind the same mutex, a single UI
  // screen alone could sustain a rate close to that limit for tens of
  // seconds straight, with no room left for any other screen's requests
  // sharing the queue. That's what produced the wall of 504s seen in
  // testing: not one-off overload, but this app's own traffic saturating
  // Jikan's window. 2500ms trades some speed for headroom, so a full grid
  // of posters actually finishes near Jikan's real capacity instead of
  // constantly getting bounced by it.
  static const _jikanGap = Duration(milliseconds: 2500);

  // Serialized via a chained-Future mutex: every _jikanGet call awaits the
  // previous one before running, so concurrent calls (e.g. detail +
  // episodes + characters + recommendations all fired from initState at
  // once) are truly one-at-a-time — not just spaced by a timestamp check,
  // which is racy when several calls start in the same event-loop tick.
  static Future<void> _jikanQueue = Future.value();

  static Future<http.Response> _jikanGet(String url) {
    final result = _jikanQueue.then((_) => _jikanGetSerial(url));
    // Swallow errors here so one failed request doesn't break the queue for
    // requests queued after it; each caller still sees its own error below.
    _jikanQueue = result.then((_) => null, onError: (_) => null);
    return result;
  }

  static Future<http.Response> _jikanGetSerial(String url) async {
    final elapsed = DateTime.now().difference(_lastJikanRequest);
    if (elapsed < _jikanGap) {
      await Future<void>.delayed(_jikanGap - elapsed);
    }
    _lastJikanRequest = DateTime.now();
    developer.log('[Jikan] GET $url', name: 'AnimeApiService');

    http.Response res;
    try {
      res = await http.get(Uri.parse(url)).timeout(const Duration(seconds: 12));
    } catch (e) {
      developer.log('[Jikan] Network error: $e', name: 'AnimeApiService', level: 1000);
      throw Exception('Jikan network error: $e');
    }

    // The AniList fallback below turned out to be fragile in a way Jikan
    // itself never is: AniList has both a hard rate limit (429) AND a
    // manual-IP-block policy for sustained bursts (see their docs — "we
    // will manually block your IP" — which is what happened during
    // testing and can take hours to clear, not seconds). Every request
    // this app fails to get from Jikan is a request that goes to that
    // fragile fallback, so it's worth spending ONE retry here — after the
    // exact gap Jikan itself expects — to recover from a transient
    // 429/5xx before giving up on the API that's actually reliable long
    // term and falling through to the one that isn't.
    if (res.statusCode == 429 || res.statusCode >= 500) {
      // ignore: avoid_print
      print('[Jikan] ${res.statusCode} for $url — retrying once after gap');
      developer.log('[Jikan] ${res.statusCode} — retrying once after gap',
          name: 'AnimeApiService');
      await Future<void>.delayed(_jikanGap);
      _lastJikanRequest = DateTime.now();
      try {
        res = await http.get(Uri.parse(url)).timeout(const Duration(seconds: 12));
      } catch (e) {
        developer.log('[Jikan] Retry network error: $e', name: 'AnimeApiService', level: 1000);
        throw Exception('Jikan network error on retry: $e');
      }
      if (res.statusCode == 429 || res.statusCode >= 500) {
        // ignore: avoid_print
        print('[Jikan] ${res.statusCode} for $url again after retry — failing to fallback');
        developer.log('[Jikan] ${res.statusCode} again after retry — failing to fallback',
            name: 'AnimeApiService');
      }
    }

    if (res.statusCode != 200) {
      // ignore: avoid_print
      print('[Jikan] HTTP ${res.statusCode} for $url');
      developer.log('[Jikan] HTTP ${res.statusCode}: ${res.body.substring(0, res.body.length.clamp(0, 300))}',
          name: 'AnimeApiService', level: 1000);
      throw Exception('Jikan HTTP ${res.statusCode} — $url');
    }
    return res;
  }

  // ── AniList fallback ──────────────────────────────────────────────────
  // Used only when Jikan itself fails (network error, 429/504 after retry,
  // etc.) — Jikan stays the primary source everywhere. AniList's GraphQL
  // API can be queried directly by MAL id (idMal), so no separate
  // MAL↔AniList id mapping table is needed.
  static const _aniListBase = 'https://graphql.anilist.co';

  // Direct requests to graphql.anilist.co from Flutter Web get blocked by
  // the browser's CORS policy (AniList sends no Access-Control-Allow-Origin
  // header for this origin) — confirmed via DevTools console:
  // "Access to fetch at 'https://graphql.anilist.co/' ... has been blocked
  // by CORS policy". Went through proxy.corsfix.com for a while, which
  // fixed the CORS block but is a proxy SHARED with every other app using
  // it — its rate limit (429s seen in testing) reacts to everyone's
  // traffic, not just this app's, so it wasn't actually a fix for the
  // underlying rate-limit problem, just a different flavor of it.
  //
  // Final fix: same self-hosted Cloudflare Worker used for MAL images
  // above (aniverse-proxy.tirtasisahid.workers.dev/anilist — see
  // worker.js), used only by AniVerse. No shared rate limit with other
  // apps; the mutex below is what actually prevents this app's OWN
  // requests from bursting AniList's per-IP limit (the Worker's IP, now,
  // consistently — not the browser's).
  static const _aniListProxyBase =
      'https://aniverse-proxy.tirtasisahid.workers.dev/anilist';

  // Same problem Jikan already solved above, one level further down the
  // fallback chain: when Jikan fails fast (by design, no retry — see
  // _jikanGetSerial) for a whole grid of posters at once, every one of
  // them calls fetchCoverByTitle → _aniListQuery in the same event-loop
  // tick, with no spacing between them at all. AniList's rate limit reacts
  // to that burst by 429-ing nearly all of them, and the per-call
  // 3-attempt/500-1200ms backoff below isn't enough headroom to absorb a
  // burst of 20-30 simultaneous requests — it just staggers the SAME
  // burst-sized wall of retries into the next window, which gets 429'd
  // again. A serial mutex queue (identical in spirit to _jikanQueue above)
  // fixes this at the source: only one AniList request is ever in flight
  // at a time, so this fallback stops recreating the exact burst pattern
  // it exists to work around.
  static Future<void> _aniListQueue = Future.value();
  static DateTime _lastAniListRequest = DateTime.fromMillisecondsSinceEpoch(0);
  static const _aniListGap = Duration(milliseconds: 1500);

  static Future<Map<String, dynamic>?> _aniListQuery(
      String query, Map<String, dynamic> variables) {
    final result = _aniListQueue.then((_) => _aniListQuerySerial(query, variables));
    // Swallow errors here so one failed request doesn't break the queue for
    // requests queued after it; each caller still sees its own null/result.
    _aniListQueue = result.then((_) => null, onError: (_) => null);
    return result;
  }

  static Future<Map<String, dynamic>?> _aniListQuerySerial(
      String query, Map<String, dynamic> variables) async {
    final elapsed = DateTime.now().difference(_lastAniListRequest);
    if (elapsed < _aniListGap) {
      await Future<void>.delayed(_aniListGap - elapsed);
    }
    _lastAniListRequest = DateTime.now();

    // A 429 here (despite the serial mutex above) means AniList's window
    // was already tight from other traffic — treated the same as any other
    // non-200 used to mean giving up for good immediately, dropping exactly
    // the requests AniList was asking us to slow down and retry. Retrying
    // after a short backoff instead lets those requests succeed once
    // AniList's window clears, rather than treating a temporary "slow down"
    // as a permanent "no".
    const maxAttempts = 3;
    for (var attempt = 0; attempt < maxAttempts; attempt++) {
      try {
        final res = await http
            .post(
              Uri.parse(_aniListProxyBase),
              headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
              },
              body: jsonEncode({'query': query, 'variables': variables}),
            )
            .timeout(const Duration(seconds: 12));
        if (res.statusCode == 429) {
          if (attempt == maxAttempts - 1) {
            developer.log('[AniList] HTTP 429, out of retries',
                name: 'AnimeApiService', level: 900);
            return null;
          }
          // Exponential-ish backoff (500ms, 1200ms) plus jitter so a whole
          // batch of throttled requests doesn't retry in perfect lockstep
          // and immediately re-trigger the same rate limit.
          final backoffMs = 500 * (attempt + 1) + Random().nextInt(300);
          await Future.delayed(Duration(milliseconds: backoffMs));
          continue;
        }
        if (res.statusCode != 200) {
          developer.log('[AniList] HTTP ${res.statusCode}', name: 'AnimeApiService', level: 900);
          return null;
        }
        final decoded = jsonDecode(res.body) as Map<String, dynamic>;
        return decoded['data'] as Map<String, dynamic>?;
      } catch (e) {
        developer.log('[AniList] error: $e', name: 'AnimeApiService', level: 900);
        return null;
      }
    }
    return null;
  }

  static const _aniListDetailQuery = r'''
query ($idMal: Int) {
  Media(idMal: $idMal, type: ANIME) {
    title { english romaji }
    description(asHtml: false)
    averageScore
    episodes
    status
    genres
    studios(isMain: true) { nodes { name } }
    coverImage { extraLarge large }
    trailer { id site }
    relations {
      edges {
        relationType
        node { idMal type title { english romaji } }
      }
    }
  }
}
''';

  static Future<JikanAnimeDetail?> _fetchAnimeDetailFromAniList(String malId) async {
    final idMal = int.tryParse(malId);
    if (idMal == null) return null;
    final data = await _aniListQuery(_aniListDetailQuery, {'idMal': idMal});
    final media = data?['Media'] as Map<String, dynamic>?;
    if (media == null) return null;

    final titleMap = media['title'] as Map<String, dynamic>? ?? {};
    final titleEn = (titleMap['english'] as String?)?.trim();
    final title = (titleEn?.isNotEmpty == true)
        ? titleEn!
        : ((titleMap['romaji'] as String?)?.trim() ?? 'Unknown Title');

    final synopsis = ((media['description'] as String?) ?? '')
        .replaceAll(RegExp(r'<[^>]*>'), '')
        .trim();

    final score = ((media['averageScore'] as num?)?.toDouble() ?? 0.0) / 10.0;
    final episodes = (media['episodes'] as num?)?.toInt();
    final status = (media['status'] as String?)?.trim() ?? 'Unknown';
    final genres = (media['genres'] as List<dynamic>? ?? []).whereType<String>().toList();

    final studioNodes =
        (media['studios'] as Map<String, dynamic>?)?['nodes'] as List<dynamic>? ?? [];
    final studios = studioNodes
        .whereType<Map<String, dynamic>>()
        .map((s) => (s['name'] as String?)?.trim())
        .whereType<String>()
        .toList();

    final cover = media['coverImage'] as Map<String, dynamic>? ?? {};
    final largeImageUrl = (cover['extraLarge'] as String?) ??
        (cover['large'] as String?) ??
        'https://placehold.co/600x800/png?text=No+Image';

    final trailer = media['trailer'] as Map<String, dynamic>?;
    final trailerYoutubeId = (trailer?['site'] == 'youtube')
        ? (trailer?['id'] as String?)
        : null;

    final relEdges = (media['relations'] as Map<String, dynamic>?)?['edges'] as List<dynamic>? ?? [];
    final relations = <RelatedAnimeModel>[];
    for (final edge in relEdges) {
      final e = edge as Map<String, dynamic>;
      final node = e['node'] as Map<String, dynamic>? ?? {};
      if (node['type'] != 'ANIME') continue;
      final relId = node['idMal']?.toString() ?? '';
      if (relId.isEmpty) continue;
      final t = node['title'] as Map<String, dynamic>? ?? {};
      final relTitle = (t['english'] as String?) ?? (t['romaji'] as String?) ?? 'Unknown';
      relations.add(RelatedAnimeModel(
        malId: relId,
        title: relTitle,
        imageUrl: 'https://placehold.co/600x400/png?text=${Uri.encodeComponent(relTitle)}',
        relationType: (e['relationType'] as String?) ?? 'Related',
      ));
      if (relations.length >= 15) break;
    }

    return JikanAnimeDetail(
      title: title,
      synopsis: synopsis.isEmpty ? 'No synopsis available.' : synopsis,
      score: score,
      rank: null,
      episodes: episodes,
      status: status,
      genres: genres.isEmpty ? const ['Unknown'] : genres,
      studios: studios,
      largeImageUrl: largeImageUrl,
      trailerYoutubeId: trailerYoutubeId,
      relations: relations,
    );
  }

  static const _aniListRecoQuery = r'''
query ($idMal: Int) {
  Media(idMal: $idMal, type: ANIME) {
    recommendations(sort: RATING_DESC, perPage: 10) {
      nodes {
        mediaRecommendation {
          idMal
          title { english romaji }
          coverImage { extraLarge large }
          averageScore
        }
      }
    }
  }
}
''';

  // ── AniList Page fallback for list endpoints ─────────────────────────────
  // Used when Jikan's list endpoints (seasons/now, top/anime, anime?genres=,
  // anime?q=) fail outright — e.g. the 504s seen when Jikan's upstream is
  // overloaded. Unlike the single-Media detail queries above, these hit
  // AniList's `Page` connection to get back a list shaped like Jikan's,
  // mapped through the same AnimeModel so callers (Home/Jadwal/Explore)
  // don't need to know which source actually answered.
  static const _aniListPageQuery = r'''
query ($search: String, $season: MediaSeason, $seasonYear: Int, $genre: String, $sort: [MediaSort], $perPage: Int) {
  Page(perPage: $perPage) {
    media(type: ANIME, search: $search, season: $season, seasonYear: $seasonYear, genre: $genre, sort: $sort) {
      idMal
      title { english romaji }
      coverImage { extraLarge large }
      averageScore
      genres
      description(asHtml: false)
      popularity
    }
  }
}
''';

  /// Minimal query used only by [fetchCoverByTitle] — deliberately omits
  /// idMal from the result shape's requirements (it's still requested for
  /// debugging, but nothing here discards a result for lacking one). See
  /// the comment in [_fetchCoverByTitle] for why this can't reuse
  /// [_aniListPageQuery] via [_mapAniListPage].
  static const _aniListCoverOnlyQuery = r'''
query ($search: String, $perPage: Int) {
  Page(perPage: $perPage) {
    media(type: ANIME, search: $search) {
      idMal
      coverImage { extraLarge large }
    }
  }
}
''';

  static List<AnimeModel> _mapAniListPage(Map<String, dynamic>? data) {
    final mediaList = (data?['Page'] as Map<String, dynamic>?)?['media'] as List<dynamic>? ?? [];
    final result = <AnimeModel>[];
    for (final item in mediaList) {
      final m = item as Map<String, dynamic>;
      final idMal = m['idMal'];
      if (idMal == null) continue; // no MAL id → can't key into the rest of the app
      final id = idMal.toString();
      final t = m['title'] as Map<String, dynamic>? ?? {};
      final title = (t['english'] as String?)?.trim().isNotEmpty == true
          ? (t['english'] as String).trim()
          : ((t['romaji'] as String?)?.trim() ?? 'Unknown Title');
      final cover = m['coverImage'] as Map<String, dynamic>? ?? {};
      final image = (cover['extraLarge'] as String?) ??
          (cover['large'] as String?) ??
          'https://placehold.co/600x800/png?text=No+Image';
      final score = ((m['averageScore'] as num?)?.toDouble() ?? 0.0) / 10.0;
      final genres = (m['genres'] as List<dynamic>? ?? []).whereType<String>().toList();
      final synopsis = ((m['description'] as String?) ?? '')
          .replaceAll(RegExp(r'<[^>]*>'), '')
          .trim();
      final popularity = (m['popularity'] as num?)?.toInt() ?? 0;

      result.add(AnimeModel(
        id: id,
        title: title,
        imageUrl: image,
        rating: score,
        genres: genres.isEmpty ? const ['Unknown'] : genres,
        description: synopsis.isEmpty ? 'No synopsis available.' : synopsis,
        isTrending: popularity >= 50000,
        episodes: const [],
        malId: int.tryParse(id),
      ));
    }
    return result;
  }

  /// AniList uses YYYY + a season enum (WINTER/SPRING/SUMMER/FALL) rather
  /// than Jikan's "now" shorthand, so the current season has to be computed
  /// on our side the same way AniList itself buckets months.
  static String _currentAniListSeasonName() {
    final month = DateTime.now().month;
    if (month <= 3) return 'WINTER';
    if (month <= 6) return 'SPRING';
    if (month <= 9) return 'SUMMER';
    return 'FALL';
  }

  static Future<List<AnimeModel>> _fetchCurrentSeasonFromAniList() async {
    final season = _currentAniListSeasonName();
    final year = DateTime.now().year;
    final data = await _aniListQuery(_aniListPageQuery, {
      'season': season,
      'seasonYear': year,
      'sort': ['POPULARITY_DESC'],
      'perPage': 25,
    });
    return _mapAniListPage(data);
  }

  static Future<List<AnimeModel>> _fetchTopAnimeFromAniList() async {
    final data = await _aniListQuery(_aniListPageQuery, {
      'sort': ['POPULARITY_DESC'],
      'perPage': 25,
    });
    return _mapAniListPage(data);
  }

  static Future<List<AnimeModel>> _fetchAnimeByGenreFromAniList(String genreName) async {
    final data = await _aniListQuery(_aniListPageQuery, {
      'genre': genreName,
      'sort': ['SCORE_DESC'],
      'perPage': 25,
    });
    return _mapAniListPage(data);
  }

  static Future<List<AnimeModel>> _searchAnimeFromAniList(String query) async {
    final data = await _aniListQuery(_aniListPageQuery, {
      'search': query,
      'perPage': 25,
    });
    return _mapAniListPage(data);
  }

  // Used as a fallback for latest-aired-episode number when Jikan's
  // /episodes endpoint returns an empty list — common for currently-airing
  // titles whose per-episode breakdown hasn't been filled in on MAL yet,
  // even though the season entry itself exists. AniList tends to have
  // nextAiringEpisode populated for these from its own airing schedule.
  static const _aniListNextEpisodeQuery = r'''
query ($idMal: Int) {
  Media(idMal: $idMal, type: ANIME) {
    episodes
    nextAiringEpisode { episode }
  }
}
''';

  /// Returns the latest episode number that has already aired, using
  /// AniList's airing schedule. `nextAiringEpisode.episode` is the episode
  /// NOT yet aired, so the latest aired one is that minus 1. If the show
  /// has no more upcoming episodes (finished airing), falls back to the
  /// total `episodes` count. Returns null if AniList has neither field
  /// populated — callers should treat that as "still unknown", not guess.
  static Future<int?> fetchLatestAiredEpisodeNumber(String malId) async {
    final idMal = int.tryParse(malId);
    if (idMal == null) return null;
    try {
      final data = await _aniListQuery(_aniListNextEpisodeQuery, {'idMal': idMal});
      final media = data?['Media'] as Map<String, dynamic>?;
      if (media == null) return null;
      final nextEp = (media['nextAiringEpisode']
          as Map<String, dynamic>?)?['episode'] as num?;
      if (nextEp != null && nextEp.toInt() > 1) return nextEp.toInt() - 1;
      final totalEpisodes = (media['episodes'] as num?)?.toInt();
      return totalEpisodes;
    } catch (e) {
      // ignore: avoid_print
      print('[fetchLatestAiredEpisodeNumber] AniList query FAILED for idMal=$idMal: $e');
      return null;
    }
  }

  static Future<List<AnimeModel>> _fetchAnimeRecommendationsFromAniList(String malId) async {
    final idMal = int.tryParse(malId);
    if (idMal == null) return const [];
    final data = await _aniListQuery(_aniListRecoQuery, {'idMal': idMal});
    final media = data?['Media'] as Map<String, dynamic>?;
    final nodes =
        (media?['recommendations'] as Map<String, dynamic>?)?['nodes'] as List<dynamic>? ?? [];

    final result = <AnimeModel>[];
    for (final n in nodes) {
      final rec = (n as Map<String, dynamic>)['mediaRecommendation'] as Map<String, dynamic>?;
      if (rec == null) continue;
      final id = rec['idMal']?.toString() ?? '';
      if (id.isEmpty) continue;
      final t = rec['title'] as Map<String, dynamic>? ?? {};
      final title = (t['english'] as String?) ?? (t['romaji'] as String?) ?? 'Unknown';
      final cover = rec['coverImage'] as Map<String, dynamic>? ?? {};
      final image = (cover['extraLarge'] as String?) ??
          (cover['large'] as String?) ??
          'https://placehold.co/600x800/png?text=No+Image';
      final score = ((rec['averageScore'] as num?)?.toDouble() ?? 0.0) / 10.0;

      result.add(AnimeModel(
        id: id,
        title: title,
        imageUrl: image,
        rating: score,
        genres: const ['Unknown'],
        description: 'No synopsis.',
        isTrending: false,
        episodes: const [],
        malId: int.tryParse(id),
      ));
      if (result.length >= 10) break;
    }
    return result;
  }

  static const _aniListCharactersQuery = r'''
query ($idMal: Int) {
  Media(idMal: $idMal, type: ANIME) {
    characters(sort: ROLE, perPage: 25) {
      edges {
        role
        node { id name { full } image { large } }
        voiceActors(language: JAPANESE) {
          name { full }
          image { large }
        }
      }
    }
  }
}
''';

  static Future<List<CharacterModel>?> _fetchAnimeCharactersFromAniList(String malId) async {
    final idMal = int.tryParse(malId);
    if (idMal == null) return null;
    final data = await _aniListQuery(_aniListCharactersQuery, {'idMal': idMal});
    final media = data?['Media'] as Map<String, dynamic>?;
    if (media == null) return null;
    final edges = (media['characters'] as Map<String, dynamic>?)?['edges'] as List<dynamic>? ?? [];

    final characters = <CharacterModel>[];
    final voiceActors = <VoiceActorModel>[];

    for (final edge in edges) {
      final e = edge as Map<String, dynamic>;
      final node = e['node'] as Map<String, dynamic>? ?? {};
      final charId = node['id']?.toString() ?? '';
      if (charId.isEmpty) continue;
      final charName = ((node['name'] as Map<String, dynamic>?)?['full'] as String?)?.trim() ?? 'Unknown';
      final charImage = ((node['image'] as Map<String, dynamic>?)?['large'] as String?) ??
          'https://placehold.co/256x256/png?text=?';
      final roleRaw = (e['role'] as String?)?.trim() ?? 'SUPPORTING';
      final role = roleRaw == 'MAIN' ? 'Main' : (roleRaw == 'BACKGROUND' ? 'Background' : 'Supporting');

      final vaListRaw = e['voiceActors'] as List<dynamic>? ?? [];
      final charVAs = <CharacterVoiceActor>[];
      for (final va in vaListRaw) {
        final vaMap = va as Map<String, dynamic>;
        final vaName = ((vaMap['name'] as Map<String, dynamic>?)?['full'] as String?)?.trim() ?? 'Unknown';
        final vaImage = ((vaMap['image'] as Map<String, dynamic>?)?['large'] as String?) ??
            'https://placehold.co/256x256/png?text=VA';

        charVAs.add(CharacterVoiceActor(name: vaName, language: 'Japanese', imageUrl: vaImage));

        // Build a Jikan-shaped map so the existing VoiceActorModel.fromJson
        // parser (which expects Jikan's native format) can be reused as-is.
        voiceActors.add(VoiceActorModel.fromJson(
          {
            'language': 'Japanese',
            'person': {
              'name': vaName,
              'images': {
                'jpg': {'image_url': vaImage},
              },
            },
          },
          characterName: charName,
          characterImageUrl: charImage,
        ));
      }

      characters.add(CharacterModel(
        malId: charId, name: charName, imageUrl: charImage,
        role: role, voiceActors: charVAs));
    }

    if (characters.isEmpty) return null;
    _vaCache[malId] = voiceActors;
    return characters;
  }
  static void clearAnimeCache(String id) {
    _detailCache.remove(id);
    _recoCache.remove(id);
    _episodeCache.remove(id);
    _charCache.remove(id);
    _vaCache.remove(id);
  }

  // ── Helper: map a Jikan "data" anime object → AnimeModel ─────────────────
  static AnimeModel _mapJikanAnime(Map<String, dynamic> m) {
    final id = m['mal_id']?.toString() ?? '';
    final titleMap = m['titles'] as List<dynamic>? ?? [];
    String? titleEn = (m['title_english'] as String?)?.trim();
    String? titleDefault = (m['title'] as String?)?.trim();
    if ((titleEn == null || titleEn.isEmpty) && titleMap.isNotEmpty) {
      titleEn = titleMap
          .whereType<Map<String, dynamic>>()
          .firstWhere((t) => t['type'] == 'English', orElse: () => {})['title']
          as String?;
    }
    final title = (titleEn?.isNotEmpty == true)
        ? titleEn!
        : (titleDefault?.isNotEmpty == true ? titleDefault! : 'Unknown Title');

    final images = m['images'] as Map<String, dynamic>? ?? {};
    final jpg = images['jpg'] as Map<String, dynamic>? ?? {};
    final cover = (jpg['large_image_url'] as String?) ??
        (jpg['image_url'] as String?) ??
        'https://placehold.co/600x800/png?text=No+Image';

    final rawScore = (m['score'] as num?)?.toDouble();
    final score = rawScore ?? 0.0;

    final genresList = (m['genres'] as List<dynamic>? ?? [])
        .whereType<Map<String, dynamic>>()
        .map((g) => (g['name'] as String?)?.trim())
        .whereType<String>()
        .toList();

    final synopsis = (m['synopsis'] as String?)?.trim() ?? '';
    final members = (m['members'] as num?)?.toInt() ?? 0;

    return AnimeModel(
      id: id,
      title: title,
      imageUrl: cover,
      rating: score,
      genres: genresList.isEmpty ? const ['Unknown'] : genresList,
      description: synopsis.isEmpty ? 'No synopsis available.' : synopsis,
      isTrending: members >= 200000,
      episodes: const [],
      malId: int.tryParse(id),
    );
  }

  static List<AnimeModel> _mapJikanList(Map<String, dynamic> decoded) {
    final data = decoded['data'] as List<dynamic>? ?? [];
    return data
        .whereType<Map<String, dynamic>>()
        .map(_mapJikanAnime)
        .where((a) => a.id.isNotEmpty)
        .toList();
  }

  // ── Top anime ──────────────────────────────────────────────────────────
  static Future<List<AnimeModel>> fetchTopAnime() async {
    const key = '__top__';
    if (_listCache.containsKey(key)) return _listCache[key]!;
    try {
      final res = await _jikanGet('$_jikanBase/top/anime?filter=bypopularity&limit=25');
      final list = _mapJikanList(jsonDecode(res.body) as Map<String, dynamic>);
      _listCache[key] = list;
      return list;
    } catch (e) {
      developer.log('[Jikan] fetchTopAnime failed, trying AniList fallback: $e',
          name: 'AnimeApiService', level: 900);
      final fallback = await _fetchTopAnimeFromAniList();
      if (fallback.isNotEmpty) _listCache[key] = fallback;
      return fallback;
    }
  }

  // ── Search ─────────────────────────────────────────────────────────────
  static Future<List<AnimeModel>> searchAnime(String query) async {
    final key = '__search__${query.toLowerCase()}';
    if (_listCache.containsKey(key)) return _listCache[key]!;
    try {
      final res = await _jikanGet(
          '$_jikanBase/anime?q=${Uri.encodeComponent(query)}&limit=25&sfw=true');
      final list = _mapJikanList(jsonDecode(res.body) as Map<String, dynamic>);
      _listCache[key] = list;
      return list;
    } catch (e) {
      developer.log('[Jikan] searchAnime failed, trying AniList fallback: $e',
          name: 'AnimeApiService', level: 900);
      final fallback = await _searchAnimeFromAniList(query);
      if (fallback.isNotEmpty) _listCache[key] = fallback;
      return fallback;
    }
  }

  // ── By genre ───────────────────────────────────────────────────────────
  // Genre IDs here are Jikan/MAL genre IDs directly — no name-based mapping
  // needed, unlike the previous AniList-based implementation. The AniList
  // fallback below needs a genre NAME (its API filters by string, not MAL's
  // numeric id), so a small reverse lookup table covers the common genres
  // this app actually uses; unmapped ids just skip the fallback rather than
  // guessing a name.
  static const Map<int, String> _jikanGenreIdToAniListName = {
    1: 'Action', 2: 'Adventure', 4: 'Comedy', 8: 'Drama', 10: 'Fantasy',
    14: 'Horror', 7: 'Mystery', 22: 'Romance', 24: 'Sci-Fi', 36: 'Slice of Life',
    30: 'Sports', 37: 'Supernatural', 41: 'Thriller',
  };

  static Future<List<AnimeModel>> fetchAnimeByGenre(int genreId) async {
    final key = '__genre__$genreId';
    if (_listCache.containsKey(key)) return _listCache[key]!;
    try {
      final res = await _jikanGet(
          '$_jikanBase/anime?genres=$genreId&order_by=score&sort=desc&limit=25&sfw=true');
      final list = _mapJikanList(jsonDecode(res.body) as Map<String, dynamic>);
      _listCache[key] = list;
      return list;
    } catch (e) {
      developer.log('[Jikan] fetchAnimeByGenre failed, trying AniList fallback: $e',
          name: 'AnimeApiService', level: 900);
      final genreName = _jikanGenreIdToAniListName[genreId];
      if (genreName == null) return const [];
      final fallback = await _fetchAnimeByGenreFromAniList(genreName);
      if (fallback.isNotEmpty) _listCache[key] = fallback;
      return fallback;
    }
  }

  // ── Current season ─────────────────────────────────────────────────────
  static Future<List<AnimeModel>> fetchCurrentSeasonAnime() async {
    const key = '__season__';
    if (_listCache.containsKey(key)) return _listCache[key]!;
    try {
      final res = await _jikanGet('$_jikanBase/seasons/now?limit=25&sfw=true');
      final list = _mapJikanList(jsonDecode(res.body) as Map<String, dynamic>);
      _listCache[key] = list;
      return list;
    } catch (e) {
      developer.log('[Jikan] fetchCurrentSeasonAnime failed, trying AniList fallback: $e',
          name: 'AnimeApiService', level: 900);
      final fallback = await _fetchCurrentSeasonFromAniList();
      if (fallback.isNotEmpty) _listCache[key] = fallback;
      return fallback;
    }
  }

  // ── Detail — Jikan /anime/{id}/full ───────────────────────────────────
  static Future<JikanAnimeDetail> fetchAnimeDetail(String malId) async {
    if (_isCustomCatalogId(malId)) {
      throw StateError('Custom catalog entry — no remote detail, use local data');
    }
    // ignore: avoid_print
    print('🟢 BUILD-CHECK v3: fetchAnimeDetail($malId) — AniList-primary code path');
    if (_detailCache.containsKey(malId)) return _detailCache[malId]!;

    final aniList = await _fetchAnimeDetailFromAniList(malId);
    if (aniList != null) {
      _detailCache[malId] = aniList;
      return aniList;
    }

    developer.log('[AniList] fetchAnimeDetail failed/empty, trying Jikan fallback',
        name: 'AnimeApiService', level: 900);
    final detail = await _fetchAnimeDetailFromJikan(malId);
    _detailCache[malId] = detail;
    return detail;
  }

  static Future<JikanAnimeDetail> _fetchAnimeDetailFromJikan(String malId) async {
    final res = await _jikanGet('$_jikanBase/anime/$malId/full');
    final decoded = jsonDecode(res.body) as Map<String, dynamic>;
    final data = decoded['data'] as Map<String, dynamic>? ?? {};

    final titleEn = (data['title_english'] as String?)?.trim();
    final titleDefault = (data['title'] as String?)?.trim();
    final title = (titleEn?.isNotEmpty == true)
        ? titleEn!
        : (titleDefault?.isNotEmpty == true ? titleDefault! : 'Unknown Title');

    final synopsis = (data['synopsis'] as String?)?.trim() ?? '';
    final score = (data['score'] as num?)?.toDouble() ?? 0.0;
    final rank = (data['rank'] as num?)?.toInt();
    final episodes = (data['episodes'] as num?)?.toInt();
    final status = (data['status'] as String?)?.trim() ?? 'Unknown';

    final genres = <String>[
      ...((data['genres'] as List<dynamic>? ?? [])
          .whereType<Map<String, dynamic>>()
          .map((g) => (g['name'] as String?)?.trim())
          .whereType<String>()),
      ...((data['explicit_genres'] as List<dynamic>? ?? [])
          .whereType<Map<String, dynamic>>()
          .map((g) => (g['name'] as String?)?.trim())
          .whereType<String>()),
    ];

    final studios = (data['studios'] as List<dynamic>? ?? [])
        .whereType<Map<String, dynamic>>()
        .map((s) => (s['name'] as String?)?.trim())
        .whereType<String>()
        .toList();

    final images = data['images'] as Map<String, dynamic>? ?? {};
    final jpg = images['jpg'] as Map<String, dynamic>? ?? {};
    final largeImageUrl = (jpg['large_image_url'] as String?) ??
        (jpg['image_url'] as String?) ??
        'https://placehold.co/600x800/png?text=No+Image';

    final trailer = data['trailer'] as Map<String, dynamic>?;
    final trailerYoutubeId = (trailer?['youtube_id'] as String?);

    // Relations
    final relationsRaw = data['relations'] as List<dynamic>? ?? [];
    final relations = <RelatedAnimeModel>[];
    for (final rel in relationsRaw) {
      final r = rel as Map<String, dynamic>;
      final relationType = (r['relation'] as String?)?.trim() ?? 'Related';
      final entries = r['entry'] as List<dynamic>? ?? [];
      for (final entry in entries) {
        final e = entry as Map<String, dynamic>;
        if ((e['type'] as String?) != 'anime') continue;
        final relId = e['mal_id']?.toString() ?? '';
        if (relId.isEmpty) continue;
        final relTitle = (e['name'] as String?)?.trim() ?? 'Unknown';
        relations.add(RelatedAnimeModel(
          malId: relId,
          title: relTitle,
          imageUrl: 'https://placehold.co/600x400/png?text=${Uri.encodeComponent(relTitle)}',
          relationType: relationType,
        ));
        if (relations.length >= 15) break;
      }
      if (relations.length >= 15) break;
    }

    return JikanAnimeDetail(
      title: title,
      synopsis: synopsis.isEmpty ? 'No synopsis available.' : synopsis,
      score: score,
      rank: rank,
      episodes: episodes,
      status: status,
      genres: genres.isEmpty ? const ['Unknown'] : genres,
      studios: studios,
      largeImageUrl: largeImageUrl,
      trailerYoutubeId: trailerYoutubeId,
      relations: relations,
    );
  }

  // ── Characters + voice actors — Jikan /anime/{id}/characters ────────────
  static Future<List<CharacterModel>> fetchAnimeCharacters(String malId, {String? title}) async {
    if (_isCustomCatalogId(malId)) {
      _charCache[malId] = const [];
      _vaCache[malId] = const [];
      return const [];
    }
    // ignore: avoid_print
    print('🟢 BUILD-CHECK v3: fetchAnimeCharacters($malId) — AniList-primary code path');
    if (_charCache.containsKey(malId)) return _charCache[malId]!;

    final aniList = await _fetchAnimeCharactersFromAniList(malId);
    if (aniList != null) {
      _charCache[malId] = aniList;
      return aniList; // _fetchAnimeCharactersFromAniList already populates _vaCache
    }

    developer.log('[AniList] fetchAnimeCharacters failed/empty, trying Jikan fallback',
        name: 'AnimeApiService', level: 900);

    final res = await _jikanGet('$_jikanBase/anime/$malId/characters');
    final decoded = jsonDecode(res.body) as Map<String, dynamic>;
    final data = decoded['data'] as List<dynamic>? ?? [];

    final characters = <CharacterModel>[];
    final voiceActors = <VoiceActorModel>[];

    for (final entry in data) {
      final e = entry as Map<String, dynamic>;
      final charNode = e['character'] as Map<String, dynamic>? ?? {};
      final charId = charNode['mal_id']?.toString() ?? '';
      if (charId.isEmpty) continue;
      final charName = (charNode['name'] as String?)?.trim() ?? 'Unknown';
      final charImages = charNode['images'] as Map<String, dynamic>? ?? {};
      final charJpg = charImages['jpg'] as Map<String, dynamic>? ?? {};
      final charImage = (charJpg['image_url'] as String?) ??
          'https://placehold.co/256x256/png?text=?';
      final role = (e['role'] as String?)?.trim() ?? 'Supporting';

      final vaListRaw = e['voice_actors'] as List<dynamic>? ?? [];
      final charVAs = <CharacterVoiceActor>[];
      for (final va in vaListRaw) {
        final vaMap = va as Map<String, dynamic>;
        final language = (vaMap['language'] as String?)?.trim() ?? '';
        final person = vaMap['person'] as Map<String, dynamic>? ?? {};
        final vaName = (person['name'] as String?)?.trim() ?? 'Unknown';
        final vaImages = person['images'] as Map<String, dynamic>? ?? {};
        final vaJpg = vaImages['jpg'] as Map<String, dynamic>? ?? {};
        final vaImage = (vaJpg['image_url'] as String?) ??
            'https://placehold.co/256x256/png?text=VA';

        charVAs.add(CharacterVoiceActor(
          name: vaName, language: language, imageUrl: vaImage));

        // vaMap is already in the exact shape VoiceActorModel.fromJson
        // expects (Jikan's native format) — no synthetic reshaping needed
        // like the old AniList-based path required.
        voiceActors.add(VoiceActorModel.fromJson(
          vaMap,
          characterName: charName,
          characterImageUrl: charImage,
        ));
      }

      characters.add(CharacterModel(
        malId: charId, name: charName, imageUrl: charImage,
        role: role, voiceActors: charVAs));
    }

    _charCache[malId] = characters;
    _vaCache[malId] = voiceActors;
    return characters;
  }

  static Future<List<VoiceActorModel>> fetchAnimeVoiceActors(String malId, {String? title}) async {
    if (_vaCache.containsKey(malId)) return _vaCache[malId]!;
    await fetchAnimeCharacters(malId, title: title); // populates both caches at once
    return _vaCache[malId] ?? [];
  }

  // ── Recommendations — Jikan /anime/{id}/recommendations ─────────────────
  static Future<List<AnimeModel>> fetchAnimeRecommendations(String malId, {String? title}) async {
    if (_isCustomCatalogId(malId)) {
      _recoCache[malId] = const [];
      return const [];
    }
    // ignore: avoid_print
    print('🟢 BUILD-CHECK v3: fetchAnimeRecommendations($malId) — AniList-primary code path');
    if (_recoCache.containsKey(malId)) return _recoCache[malId]!;

    final aniList = await _fetchAnimeRecommendationsFromAniList(malId);
    if (aniList.isNotEmpty) {
      _recoCache[malId] = aniList;
      return aniList;
    }

    developer.log('[AniList] fetchAnimeRecommendations empty/failed, trying Jikan fallback',
        name: 'AnimeApiService', level: 900);

    try {
      final res = await _jikanGet('$_jikanBase/anime/$malId/recommendations');
      final decoded = jsonDecode(res.body) as Map<String, dynamic>;
      final data = decoded['data'] as List<dynamic>? ?? [];

      final result = <AnimeModel>[];
      for (final item in data.take(10)) {
        final entry = (item as Map<String, dynamic>)['entry'] as Map<String, dynamic>?;
        if (entry == null) continue;
        final id = entry['mal_id']?.toString() ?? '';
        if (id.isEmpty) continue;
        final title = (entry['title'] as String?)?.trim() ?? 'Unknown';
        final images = entry['images'] as Map<String, dynamic>? ?? {};
        final jpg = images['jpg'] as Map<String, dynamic>? ?? {};
        final image = (jpg['large_image_url'] as String?) ??
            (jpg['image_url'] as String?) ??
            'https://placehold.co/600x800/png?text=No+Image';

        result.add(AnimeModel(
          id: id,
          title: title,
          imageUrl: image,
          rating: 0.0, // Jikan recommendations don't include score
          genres: const ['Unknown'],
          description: 'No synopsis.',
          isTrending: false,
          episodes: const [],
          malId: int.tryParse(id),
        ));
      }
      _recoCache[malId] = result;
      return result;
    } catch (e) {
      developer.log('[Jikan] fetchAnimeRecommendations error: $e',
          name: 'AnimeApiService', level: 900);
      return const [];
    }
  }

  // ── Episodes — Jikan /anime/{id}/episodes ────────────────────────────────
  static Future<List<EpisodeModel>> fetchAnimeEpisodes(String id) async {
    if (_isCustomCatalogId(id)) {
      _episodeCache[id] = const [];
      return const [];
    }
    if (_episodeCache.containsKey(id)) return _episodeCache[id]!;
    try {
      final res = await _jikanGet('$_jikanBase/anime/$id/episodes');
      final decoded = jsonDecode(res.body) as Map<String, dynamic>;
      final data = decoded['data'] as List<dynamic>? ?? [];
      // ignore: avoid_print
      print('[fetchAnimeEpisodes] id=$id raw data.length=${data.length}');

      final list = data.asMap().entries.map((entry) {
        final i = entry.key;
        final map = entry.value as Map<String, dynamic>;
        final title = (map['title'] as String?)?.trim();
        final airedRaw = (map['aired'] as String?)?.trim();
        final airedDate = airedRaw?.isNotEmpty == true
            ? airedRaw!.split('T').first : null;
        return EpisodeModel(
          number: i + 1,
          title: (title == null || title.isEmpty) ? 'Episode ${i + 1}' : title,
          duration: airedDate ?? 'N/A',
          thumbnailUrl: 'https://placehold.co/320x180/png?text=Episode+${i + 1}',
          airedDate: airedDate,
        );
      }).toList();

      if (list.isEmpty) {
        // Jikan's per-episode breakdown is empty — common for currently
        // airing titles not yet fully catalogued on MAL. Try AniList's
        // airing schedule for just the latest-aired episode number rather
        // than giving up; this is a single-entry placeholder list (not a
        // real episode list), enough for the "which episode just aired"
        // use case (e.g. Jadwal's watched-toggle sync into Library).
        // ignore: avoid_print
        print('[fetchAnimeEpisodes] id=$id Jikan empty, trying AniList fallback');
        final latest = await fetchLatestAiredEpisodeNumber(id);
        if (latest != null && latest > 0) {
          // ignore: avoid_print
          print('[fetchAnimeEpisodes] id=$id AniList fallback got episode=$latest');
          final fallbackList = [
            EpisodeModel(
              number: latest,
              title: 'Episode $latest',
              duration: 'N/A',
              thumbnailUrl: 'https://placehold.co/320x180/png?text=Episode+$latest',
            ),
          ];
          _episodeCache[id] = fallbackList;
          return fallbackList;
        }
        // ignore: avoid_print
        print('[fetchAnimeEpisodes] id=$id AniList fallback also empty/failed');
      }

      _episodeCache[id] = list;
      return list;
    } catch (e) {
      // ignore: avoid_print
      print('[fetchAnimeEpisodes] id=$id FAILED: $e');
      developer.log('[Jikan] fetchAnimeEpisodes error id=$id: $e',
          name: 'AnimeApiService', level: 900);
      return const [];
    }
  }

  // ── Reviews — Jikan /anime/{id}/reviews ──────────────────────────────────
  static Future<List<ReviewModel>> fetchAnimeReviews(String id) async {
    if (_isCustomCatalogId(id)) return const [];
    final res = await _jikanGet('$_jikanBase/anime/$id/reviews');
    final decoded = jsonDecode(res.body) as Map<String, dynamic>;
    final data = decoded['data'] as List<dynamic>? ?? [];

    return data.map((item) {
      final map = item as Map<String, dynamic>;
      final user = map['user'] as Map<String, dynamic>? ?? {};
      final username = (user['username'] as String?)?.trim() ?? 'Anonymous';
      final images = user['images'] as Map<String, dynamic>? ?? {};
      final jpg = images['jpg'] as Map<String, dynamic>? ?? {};
      final userImageUrl = (jpg['image_url'] as String?) ??
          'https://placehold.co/64x64/png?text=?';
      final score = (map['score'] as num?)?.toInt() ?? 0;
      final review = (map['review'] as String?)?.trim() ?? '';
      final dateRaw = (map['date'] as String?)?.trim() ?? '';
      final date = dateRaw.isNotEmpty ? dateRaw.split('T').first : '';
      return ReviewModel(
        username: username, userImageUrl: userImageUrl,
        score: score, review: review, date: date,
      );
    }).where((r) => r.review.isNotEmpty).toList();
  }

  // ── Resolve MAL id by title — used so custom-catalog entries can still
  // get real recommendations/characters from Jikan by matching on title ────
  static final Map<String, String?> _resolvedMalIdCache = {};

  static const _aniListSearchQuery = r'''
    query ($search: String) {
      Media(search: $search, type: ANIME) {
        idMal
      }
    }
  ''';

  static Future<String?> _resolveMalIdByTitle(String title) async {
    final key = title.trim().toLowerCase();
    if (_resolvedMalIdCache.containsKey(key)) {
      // ignore: avoid_print
      print('🟠 RESOLVE-CHECK: cache hit for "$title" -> ${_resolvedMalIdCache[key]}');
      return _resolvedMalIdCache[key];
    }

    // Try AniList first — it has held up better than Jikan under upstream load.
    try {
      // ignore: avoid_print
      print('🟠 RESOLVE-CHECK: searching AniList for title "$title"...');
      final data = await _aniListQuery(_aniListSearchQuery, {'search': title});
      final idMal = (data?['Media'] as Map<String, dynamic>?)?['idMal'];
      if (idMal != null) {
        final malId = idMal.toString();
        // ignore: avoid_print
        print('🟠 RESOLVE-CHECK: AniList resolved "$title" -> malId=$malId');
        _resolvedMalIdCache[key] = malId;
        return malId;
      }
      // ignore: avoid_print
      print('🟠 RESOLVE-CHECK: AniList found no idMal for "$title", trying Jikan');
    } catch (e) {
      // ignore: avoid_print
      print('🟠 RESOLVE-CHECK: AniList search threw for "$title" -> $e, trying Jikan');
    }

    // Fallback: Jikan title search.
    try {
      // ignore: avoid_print
      print('🟠 RESOLVE-CHECK: searching Jikan for title "$title"...');
      final res = await _jikanGet(
          '$_jikanBase/anime?q=${Uri.encodeComponent(title)}&limit=1&sfw=true');
      // ignore: avoid_print
      print('🟠 RESOLVE-CHECK: Jikan responded status=${res.statusCode} bodyLen=${res.body.length}');
      final decoded = jsonDecode(res.body) as Map<String, dynamic>;
      final data = decoded['data'] as List<dynamic>? ?? [];
      if (data.isEmpty) {
        // ignore: avoid_print
        print('🟠 RESOLVE-CHECK: no results for "$title"');
        _resolvedMalIdCache[key] = null;
        return null;
      }
      final first = data.first as Map<String, dynamic>;
      final malId = first['mal_id']?.toString();
      // ignore: avoid_print
      print('🟠 RESOLVE-CHECK: Jikan resolved "$title" -> malId=$malId');
      _resolvedMalIdCache[key] = malId;
      return malId;
    } catch (e) {
      // ignore: avoid_print
      print('🟠 RESOLVE-CHECK: threw for "$title" -> $e');
      _resolvedMalIdCache[key] = null;
      return null;
    }
  }

  // ── Cover by title — Jikan search, take first result's image ────────────
  static final Map<String, Future<String?>> _coverInFlight = {};

  static Future<String?> fetchCoverByTitle(String title) async {
    final key = title.trim().toLowerCase();
    if (key.isEmpty || key.startsWith('custom-')) return null;
    if (_coverCache.containsKey(key)) return _coverCache[key];
    return _coverInFlight.putIfAbsent(key, () => _fetchCoverByTitle(key, title));
  }

  static Future<String?> _fetchCoverByTitle(String key, String title) async {
    try {
      // AniList first — separate CDN from MAL's, already CORS-friendly, and
      // not subject to the Jikan 504s currently seen when MAL's own upstream
      // is overloaded. See file header / ProxiedNetworkImage for why this
      // matters: the whole point of this fallback is to escape MAL's CDN,
      // so searching MAL (Jikan) again first defeats the purpose.
      //
      // NOTE: deliberately NOT reusing _searchAnimeFromAniList() here — that
      // helper (via _mapAniListPage) discards any result missing an idMal,
      // which is meant for building full AnimeModel list entries. Here we
      // only need a cover image, so a result without idMal is still usable
      // and skipping it was silently causing generic-title searches (e.g.
      // "Attack on Titan", "Jujutsu Kaisen") to fall through to Jikan/
      // placeholder even though AniList had a perfectly good cover.
      try {
        final data = await _aniListQuery(_aniListCoverOnlyQuery, {
          'search': title,
          'perPage': 5,
        });
        final mediaList = (data?['Page'] as Map<String, dynamic>?)?['media']
                as List<dynamic>? ??
            [];
        for (final item in mediaList) {
          final m = item as Map<String, dynamic>;
          final cover = m['coverImage'] as Map<String, dynamic>? ?? {};
          final url =
              (cover['extraLarge'] as String?) ?? (cover['large'] as String?);
          if (url != null && url.isNotEmpty) {
            _coverCache[key] = url;
            return url;
          }
        }
      } catch (e) {
        developer.log('[fetchCoverByTitle] AniList failed for "$title": $e',
            name: 'AnimeApiService', level: 900);
      }

      // Jikan fallback — only reached if AniList had nothing.
      final res = await _jikanGet(
          '$_jikanBase/anime?q=${Uri.encodeComponent(title)}&limit=1&sfw=true');
      final decoded = jsonDecode(res.body) as Map<String, dynamic>;
      final data = decoded['data'] as List<dynamic>? ?? [];
      if (data.isEmpty) {
        _coverCache[key] = null;
        return null;
      }
      final first = data.first as Map<String, dynamic>;
      final images = first['images'] as Map<String, dynamic>? ?? {};
      final jpg = images['jpg'] as Map<String, dynamic>? ?? {};
      final url = (jpg['large_image_url'] as String?) ?? (jpg['image_url'] as String?);
      _coverCache[key] = url;
      return url;
    } catch (_) {
      _coverCache[key] = null;
      return null;
    } finally {
      _coverInFlight.remove(key);
    }
  }

  // ── Broadcast schedule helper (dipertahankan agar tidak breaking change) ─
  static const Map<String, int> _dayNameToIso = {
    'mondays': 1, 'monday': 1, 'tuesdays': 2, 'tuesday': 2,
    'wednesdays': 3, 'wednesday': 3, 'thursdays': 4, 'thursday': 4,
    'fridays': 5, 'friday': 5, 'saturdays': 6, 'saturday': 6,
    'sundays': 7, 'sunday': 7,
  };
}
