// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4wyU7Ah9084PqnY8w0R6nNv5cKtVxSYE',
    appId: '1:30870693875:web:99ac0f991df238d3c4d486',
    messagingSenderId: '30870693875',
    projectId: 'my-aniverse',
    authDomain: 'my-aniverse.firebaseapp.com',
    storageBucket: 'my-aniverse.firebasestorage.app',
    measurementId: 'G-Y6ZSSZYL7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGrZ096EuKlk8Fl9FiiirFdbjoAePqxKk',
    appId: '1:30870693875:android:47aa4661eefca5adc4d486',
    messagingSenderId: '30870693875',
    projectId: 'my-aniverse',
    storageBucket: 'my-aniverse.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjIXWEL71a4TT9fv8hZt51CjN8SvnxacQ',
    appId: '1:30870693875:ios:e369739ca32178b1c4d486',
    messagingSenderId: '30870693875',
    projectId: 'my-aniverse',
    storageBucket: 'my-aniverse.firebasestorage.app',
    iosBundleId: 'my.aniverse.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjIXWEL71a4TT9fv8hZt51CjN8SvnxacQ',
    appId: '1:30870693875:ios:e369739ca32178b1c4d486',
    messagingSenderId: '30870693875',
    projectId: 'my-aniverse',
    storageBucket: 'my-aniverse.firebasestorage.app',
    iosBundleId: 'my.aniverse.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4wyU7Ah9084PqnY8w0R6nNv5cKtVxSYE',
    appId: '1:30870693875:web:3166c766002daa06c4d486',
    messagingSenderId: '30870693875',
    projectId: 'my-aniverse',
    authDomain: 'my-aniverse.firebaseapp.com',
    storageBucket: 'my-aniverse.firebasestorage.app',
    measurementId: 'G-2V6409HWPF',
  );
}
